/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtRouteImport } from './routes/art'
import { Route as ClothingRouteImport } from './routes/clothing'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NalandaRouteImport } from './routes/nalanda'
import { Route as PlacesRouteImport } from './routes/places'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothingRoute = ClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NalandaRoute = NalandaRouteImport.update({
  id: '/nalanda',
  path: '/nalanda',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/art': typeof ArtRoute
  '/clothing': typeof ClothingRoute
  '/festivals': typeof FestivalsRoute
  '/music': typeof MusicRoute
  '/nalanda': typeof NalandaRoute
  '/places': typeof PlacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/art': typeof ArtRoute
  '/clothing': typeof ClothingRoute
  '/festivals': typeof FestivalsRoute
  '/music': typeof MusicRoute
  '/nalanda': typeof NalandaRoute
  '/places': typeof PlacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/art': typeof ArtRoute
  '/clothing': typeof ClothingRoute
  '/festivals': typeof FestivalsRoute
  '/music': typeof MusicRoute
  '/nalanda': typeof NalandaRoute
  '/places': typeof PlacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/art'
    | '/clothing'
    | '/festivals'
    | '/music'
    | '/nalanda'
    | '/places'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/art'
    | '/clothing'
    | '/festivals'
    | '/music'
    | '/nalanda'
    | '/places'
  id:
    | '__root__'
    | '/'
    | '/art'
    | '/clothing'
    | '/festivals'
    | '/music'
    | '/nalanda'
    | '/places'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtRoute: typeof ArtRoute
  ClothingRoute: typeof ClothingRoute
  FestivalsRoute: typeof FestivalsRoute
  MusicRoute: typeof MusicRoute
  NalandaRoute: typeof NalandaRoute
  PlacesRoute: typeof PlacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothing': {
      id: '/clothing'
      path: '/clothing'
      fullPath: '/clothing'
      preLoaderRoute: typeof ClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nalanda': {
      id: '/nalanda'
      path: '/nalanda'
      fullPath: '/nalanda'
      preLoaderRoute: typeof NalandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtRoute: ArtRoute,
  ClothingRoute: ClothingRoute,
  FestivalsRoute: FestivalsRoute,
  MusicRoute: MusicRoute,
  NalandaRoute: NalandaRoute,
  PlacesRoute: PlacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
